ubuntu18:
  build: .
  dockerfile: Dockerfile
  ports:
   - '8084:8080'
  environment:
    SERVER_LOG_MINIMAL: 1
    SERVER_APP_NAME: docker-test-ubuntu-18.04
    S6_KILL_FINISH_MAXTIME: 1
    S6_KILL_GRACETIME: 1
